### PR TITLE
Toolschains: fix -E preprocessor

### PR DESCRIPTION
**Pull request by ghost**
Only run flang1 in preprocessor mode when -Mpreprocess is given.

Currently pending testing.

### CODE REVIEW

**Comment by ghost** [comment]
I'm having trouble figuring out how to access the input filename from here.

**Comment by ghost** [comment]
Almost done, I think. Now I just need the output filename.

**Comment by xoviat** [comment]
I tested this with the simple case, but now I get:

```
[38/782] cmd.exe /C "C:\Users\Geoffrey\Miniconda3\Library\bin\flang.exe -cpp -DHOST_WIN -DMAXCPUS=256 -DMAXCPUSL=8 -DMAXCPUSR=8 -DNATIVE_FPCVT -DPGF90 -DPGFLANG -DPGI_LITTLE_ENDIAN -DTARGET_LLVM -DTARGET_WIN -DTARGET_WIN_X86 -DTARGET_WIN_X8664 -DTARGET_X8664 -DUNICODE -DWIN32 -DWIN64 -DWINNT -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DEBUG_POINTER_IMPL="" -D_GNU_SOURCE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DHAVE_LONG_LONG_INT -DINT32PTR64 -DTARGET_WIN_X8664 -DTM_I8 -I..\include -Iinclude -IC:\Users\Geoffrey\Miniconda3\Library\include -I..\runtime\include -I..\runtime\flang -Iruntime\flang -B C:/Users/Geoffrey/workspace/flang/build/./bin  -no-flang-libs -Jruntime\flang   -Mreentrant -E ..\runtime\flang\gather_real4.F95 -o runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95 && C:\Users\Geoffrey\Miniconda3\Library\bin\cmake.exe -E cmake_ninja_depends --tdi=runtime\flang\CMakeFiles\flang_static.dir\FortranDependInfo.json --pp=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95 --dep=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95.d --obj=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95.obj --ddi=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95.ddi"
FAILED: runtime/flang/CMakeFiles/flang_static.dir/gather_real4.F95-pp.f95 runtime/flang/CMakeFiles/flang_static.dir/gather_real4.F95-pp.f95.ddi 
cmd.exe /C "C:\Users\Geoffrey\Miniconda3\Library\bin\flang.exe -cpp -DHOST_WIN -DMAXCPUS=256 -DMAXCPUSL=8 -DMAXCPUSR=8 -DNATIVE_FPCVT -DPGF90 -DPGFLANG -DPGI_LITTLE_ENDIAN -DTARGET_LLVM -DTARGET_WIN -DTARGET_WIN_X86 -DTARGET_WIN_X8664 -DTARGET_X8664 -DUNICODE -DWIN32 -DWIN64 -DWINNT -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DEBUG_POINTER_IMPL="" -D_GNU_SOURCE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DHAVE_LONG_LONG_INT -DINT32PTR64 -DTARGET_WIN_X8664 -DTM_I8 -I..\include -Iinclude -IC:\Users\Geoffrey\Miniconda3\Library\include -I..\runtime\include -I..\runtime\flang -Iruntime\flang -B C:/Users/Geoffrey/workspace/flang/build/./bin  -no-flang-libs -Jruntime\flang   -Mreentrant -E ..\runtime\flang\gather_real4.F95 -o runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95 && C:\Users\Geoffrey\Miniconda3\Library\bin\cmake.exe -E cmake_ninja_depends --tdi=runtime\flang\CMakeFiles\flang_static.dir\FortranDependInfo.json --pp=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95 --dep=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95.d --obj=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95.obj --ddi=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95.ddi"
flang.exe: warning: argument unused during compilation: '-no-flang-libs' [-Wunused-command-line-argument]
flang.exe: error: unable to execute command: Unable to convert command-line to UTF-16: No mapping for the Unicode character exists in the target multi-byte code page.  (0x459)
```

**Comment by ghost** [comment]
I tested this with the simple case, but now I get:

```
[38/782] cmd.exe /C "C:\Users\User\Miniconda3\Library\bin\flang.exe -cpp -DHOST_WIN -DMAXCPUS=256 -DMAXCPUSL=8 -DMAXCPUSR=8 -DNATIVE_FPCVT -DPGF90 -DPGFLANG -DPGI_LITTLE_ENDIAN -DTARGET_LLVM -DTARGET_WIN -DTARGET_WIN_X86 -DTARGET_WIN_X8664 -DTARGET_X8664 -DUNICODE -DWIN32 -DWIN64 -DWINNT -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DEBUG_POINTER_IMPL="" -D_GNU_SOURCE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DHAVE_LONG_LONG_INT -DINT32PTR64 -DTARGET_WIN_X8664 -DTM_I8 -I..\include -Iinclude -IC:\Users\User\Miniconda3\Library\include -I..\runtime\include -I..\runtime\flang -Iruntime\flang -B C:/Users/User/workspace/flang/build/./bin  -no-flang-libs -Jruntime\flang   -Mreentrant -E ..\runtime\flang\gather_real4.F95 -o runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95 && C:\Users\User\Miniconda3\Library\bin\cmake.exe -E cmake_ninja_depends --tdi=runtime\flang\CMakeFiles\flang_static.dir\FortranDependInfo.json --pp=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95 --dep=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95.d --obj=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95.obj --ddi=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95.ddi"
FAILED: runtime/flang/CMakeFiles/flang_static.dir/gather_real4.F95-pp.f95 runtime/flang/CMakeFiles/flang_static.dir/gather_real4.F95-pp.f95.ddi 
cmd.exe /C "C:\Users\User\Miniconda3\Library\bin\flang.exe -cpp -DHOST_WIN -DMAXCPUS=256 -DMAXCPUSL=8 -DMAXCPUSR=8 -DNATIVE_FPCVT -DPGF90 -DPGFLANG -DPGI_LITTLE_ENDIAN -DTARGET_LLVM -DTARGET_WIN -DTARGET_WIN_X86 -DTARGET_WIN_X8664 -DTARGET_X8664 -DUNICODE -DWIN32 -DWIN64 -DWINNT -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DEBUG_POINTER_IMPL="" -D_GNU_SOURCE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DHAVE_LONG_LONG_INT -DINT32PTR64 -DTARGET_WIN_X8664 -DTM_I8 -I..\include -Iinclude -IC:\Users\User\Miniconda3\Library\include -I..\runtime\include -I..\runtime\flang -Iruntime\flang -B C:/Users/User/workspace/flang/build/./bin  -no-flang-libs -Jruntime\flang   -Mreentrant -E ..\runtime\flang\gather_real4.F95 -o runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95 && C:\Users\User\Miniconda3\Library\bin\cmake.exe -E cmake_ninja_depends --tdi=runtime\flang\CMakeFiles\flang_static.dir\FortranDependInfo.json --pp=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95 --dep=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95.d --obj=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95.obj --ddi=runtime\flang\CMakeFiles\flang_static.dir\gather_real4.F95-pp.f95.ddi"
flang.exe: warning: argument unused during compilation: '-no-flang-libs' [-Wunused-command-line-argument]
flang.exe: error: unable to execute command: Unable to convert command-line to UTF-16: No mapping for the Unicode character exists in the target multi-byte code page.  (0x459)
```

**Comment by ghost** [comment]
Tested; merging.

**Pull request merged**
